services:
  signup-service:
    build: .
    container_name: signup_service

    ports:
      - "9001:9001"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    restart: unless-stopped